# Screen 4 Non-Supernatant Pre-processing
    
    Media = tp

# Imports

In [1]:
import numpy as np
import pandas as pd
import os


import matplotlib.pyplot as plt
%matplotlib inline

import matplotlib.gridspec as gridspec

import seaborn as sns
sns.set(style='whitegrid')

from os.path import join as pjoin 
import itertools as it

%config InteractiveShell.ast_node_interactivity='all'
%config InlineBackend.figure_format = 'svg'

In [2]:
pd.set_option('max_rows', 10)

# Data

In [3]:
path  = '../data_o/screens/sc4/non_supernatant'
sc4 = 'Screen4_parsed_results_non-supernatant.tsv'

# Pre-processing

In [4]:
dfscr = pd.read_csv(pjoin(path,sc4), sep='\t', parse_dates=['Sampling_date', 'Sampling_datetime'])
dfscr['Media'].unique()

array(['tp'], dtype=object)

In [5]:
# dfscr['chlamy_bact_ratio'].unique()
# dfscr['Condition'].unique()

# lowercase
dfscr.columns = map(str.lower, dfscr.columns)



# drop columns

keep_cols = ['sampling_datetime','t (h)', 'condition', 'chlamy_bact_ratio','replicate',
             'well',  'sample',  'measurement_type', 'wavelength', 'measurement',
             'measurement_blank_average', 'measurement_fixed']


dfscr = dfscr[keep_cols]

# drop duplicates
dfscr = dfscr.drop_duplicates()

# rename columns
rename_cols =  {'sampling_datetime':'samp_day', 'sample':'content', 't (h)':'t(h)',
                'measurement':'measure', 'chlamy_bact_ratio':'c_b_ratio', 
                'measurement_blank_average':'blank_mean','measurement_fixed':'corr_measure'}
dfscr = dfscr.rename(rename_cols, axis=1)


#rename & lowercase 'measurement_type'
type_rename = {'Fluorescence Bottom Reading': 'fluorescence', 'Absorbance':'absorbance'}
dfscr['measurement_type'] = dfscr['measurement_type'].map(type_rename)


# change ratio value 
#ratio_revalue = {'-':'1', '1.6':'1.6', '16':'16', '160':'160'}
#dfscr['c_b_ratio'] = dfscr['c_b_ratio'].map(ratio_revalue)

# replicate revalue
replicate_revalue = {'rep-1':1, 'rep-2':2}
dfscr['replicate'] = dfscr['replicate'].map(replicate_revalue)
# # convert categorical int values to string types
# dfscr['replicate'] = dfscr['replicate'].map(str)

dfscr['t(h)'] = dfscr['t(h)'].map(int)

# rename and lowercase wavelength values
wave_rename = {'Ex:440_nm/Em:680_nm':'680_nm', '750_nm':'750_nm', '680_nm':'680_nm'}
dfscr['wavelength'] = dfscr['wavelength'].map(wave_rename)

# sort values by using the measurement times
dfscr = dfscr.sort_values(by=['samp_day', 'condition', 'replicate', 'c_b_ratio'])

dfscr = dfscr.reset_index(drop=True)

In [6]:
dfscr.head()
dfscr[dfscr['condition']=='b+c']
dfscr[dfscr['condition']=='sc+c']

,samp_day,t(h),condition,c_b_ratio,replicate,well,content,measurement_type,wavelength,measure,blank_mean,corr_measure
0,2019-04-16 18:19:20,0,b+c,160,2,A1,ICL_186B,absorbance,680_nm,0.1697,0.106327,0.063373
1,2019-04-16 18:19:20,0,b+c,160,2,B1,ICL_129B,absorbance,680_nm,0.1641,0.106327,0.057773
2,2019-04-16 18:19:20,0,b+c,160,2,C1,ICL_100,absorbance,680_nm,0.1565,0.106327,0.050173
3,2019-04-16 18:19:20,0,b+c,160,2,D1,ICL_101,absorbance,680_nm,0.1552,0.106327,0.048873
4,2019-04-16 18:19:20,0,b+c,160,2,E1,ICL_103,absorbance,680_nm,0.1558,0.106327,0.049473

,samp_day,t(h),condition,c_b_ratio,replicate,well,content,measurement_type,wavelength,measure,blank_mean,corr_measure
0,2019-04-16 18:19:20,0,b+c,160,2,A1,ICL_186B,absorbance,680_nm,0.1697,0.106327,0.063373
1,2019-04-16 18:19:20,0,b+c,160,2,B1,ICL_129B,absorbance,680_nm,0.1641,0.106327,0.057773
2,2019-04-16 18:19:20,0,b+c,160,2,C1,ICL_100,absorbance,680_nm,0.1565,0.106327,0.050173
3,2019-04-16 18:19:20,0,b+c,160,2,D1,ICL_101,absorbance,680_nm,0.1552,0.106327,0.048873
4,2019-04-16 18:19:20,0,b+c,160,2,E1,ICL_103,absorbance,680_nm,0.1558,0.106327,0.049473
...,...,...,...,...,...,...,...,...,...,...,...,...
24571,2019-04-23 12:44:48,162,b+c,16,1,D12,ICL_129A,fluorescence,680_nm,852.0000,277.500000,574.500000
24572,2019-04-23 12:44:48,162,b+c,16,1,E12,ICL_184BA,fluorescence,680_nm,874.0000,277.500000,596.500000
24573,2019-04-23 12:44:48,162,b+c,16,1,F12,ICL_20BA,fluorescence,680_nm,906.0000,277.500000,628.500000
24574,2019-04-23 12:44:48,162,b+c,16,1,G12,ICL_162,fluorescence,680_nm,971.0000,277.500000,693.500000
24575,2019-04-23 12:44:48,162,b+c,16,1,H12,CHLAMY,fluorescence,680_nm,830.0000,277.500000,552.500000

,samp_day,t(h),condition,c_b_ratio,replicate,well,content,measurement_type,wavelength,measure,blank_mean,corr_measure
576,2019-04-16 18:30:29,0,sc+c,160,1,A1,ICL_186B,absorbance,680_nm,0.0898,0.110357,-0.020557
577,2019-04-16 18:30:29,0,sc+c,160,1,B1,ICL_129B,absorbance,680_nm,0.0994,0.110357,-0.010957
578,2019-04-16 18:30:29,0,sc+c,160,1,C1,ICL_100,absorbance,680_nm,0.0949,0.110357,-0.015457
579,2019-04-16 18:30:29,0,sc+c,160,1,D1,ICL_101,absorbance,680_nm,0.0928,0.110357,-0.017557
580,2019-04-16 18:30:29,0,sc+c,160,1,E1,ICL_103,absorbance,680_nm,0.0933,0.110357,-0.017057
...,...,...,...,...,...,...,...,...,...,...,...,...
24859,2019-04-23 12:49:23,162,sc+c,160,1,D12,ICL_129A,fluorescence,680_nm,2.0000,277.500000,-275.500000
24860,2019-04-23 12:49:23,162,sc+c,160,1,E12,ICL_184BA,fluorescence,680_nm,726.0000,277.500000,448.500000
24861,2019-04-23 12:49:23,162,sc+c,160,1,F12,ICL_20BA,fluorescence,680_nm,942.0000,277.500000,664.500000
24862,2019-04-23 12:49:23,162,sc+c,160,1,G12,ICL_162,fluorescence,680_nm,719.0000,277.500000,441.500000
24863,2019-04-23 12:49:23,162,sc+c,160,1,H12,CHLAMY,fluorescence,680_nm,727.0000,277.500000,449.500000

## Correct Values Using 'BLANK'

In [7]:
# use the first days averages of blanks by condition and wavelength and apply it to subsequent days
gb = dfscr[(dfscr['samp_day']<='2019-04-17') &
           (dfscr['content']=='BLANK')].groupby(by=['measurement_type', 'wavelength'])


correcting_dict={}
for name,group in gb:
    correcting_dict[name]=group['measure'].mean()

gb = dfscr.groupby(['measurement_type', 'wavelength'])


groups = []
for name,group in gb:
    group = group.copy()
    group['blank_mean'] = correcting_dict[name]
    group['corr_measure'] = group['measure'] - group['blank_mean']
    groups.append(group)
    

dfscr = pd.concat(groups).sort_values(by=['samp_day', 'condition', 
                                          'replicate', 'c_b_ratio'])

# Save to Disk

In [8]:
path  = '../data_o/screens/sc4/non_supernatant'
fname = 'screen_4_non-supernatant_parsed_data.csv '


#dfscr.to_csv(pjoin(path, fname))

In [9]:
# round datetimes
dfscr['samp_day'] = dfscr['samp_day'].dt.round('D')
dfscr.head()

,samp_day,t(h),condition,c_b_ratio,replicate,well,content,measurement_type,wavelength,measure,blank_mean,corr_measure
0,2019-04-17,0,b+c,160,2,A1,ICL_186B,absorbance,680_nm,0.1697,0.109013,0.060687
1,2019-04-17,0,b+c,160,2,B1,ICL_129B,absorbance,680_nm,0.1641,0.109013,0.055087
2,2019-04-17,0,b+c,160,2,C1,ICL_100,absorbance,680_nm,0.1565,0.109013,0.047487
3,2019-04-17,0,b+c,160,2,D1,ICL_101,absorbance,680_nm,0.1552,0.109013,0.046187
4,2019-04-17,0,b+c,160,2,E1,ICL_103,absorbance,680_nm,0.1558,0.109013,0.046787

In [10]:
dfscr[dfscr['condition']=='b+c']
dfscr[dfscr['condition']=='sc+c']

,samp_day,t(h),condition,c_b_ratio,replicate,well,content,measurement_type,wavelength,measure,blank_mean,corr_measure
0,2019-04-17,0,b+c,160,2,A1,ICL_186B,absorbance,680_nm,0.1697,0.109013,0.060687
1,2019-04-17,0,b+c,160,2,B1,ICL_129B,absorbance,680_nm,0.1641,0.109013,0.055087
2,2019-04-17,0,b+c,160,2,C1,ICL_100,absorbance,680_nm,0.1565,0.109013,0.047487
3,2019-04-17,0,b+c,160,2,D1,ICL_101,absorbance,680_nm,0.1552,0.109013,0.046187
4,2019-04-17,0,b+c,160,2,E1,ICL_103,absorbance,680_nm,0.1558,0.109013,0.046787
...,...,...,...,...,...,...,...,...,...,...,...,...
24571,2019-04-24,162,b+c,16,1,D12,ICL_129A,fluorescence,680_nm,852.0000,3.424242,848.575758
24572,2019-04-24,162,b+c,16,1,E12,ICL_184BA,fluorescence,680_nm,874.0000,3.424242,870.575758
24573,2019-04-24,162,b+c,16,1,F12,ICL_20BA,fluorescence,680_nm,906.0000,3.424242,902.575758
24574,2019-04-24,162,b+c,16,1,G12,ICL_162,fluorescence,680_nm,971.0000,3.424242,967.575758
24575,2019-04-24,162,b+c,16,1,H12,CHLAMY,fluorescence,680_nm,830.0000,3.424242,826.575758

,samp_day,t(h),condition,c_b_ratio,replicate,well,content,measurement_type,wavelength,measure,blank_mean,corr_measure
576,2019-04-17,0,sc+c,160,1,A1,ICL_186B,absorbance,680_nm,0.0898,0.109013,-0.019213
577,2019-04-17,0,sc+c,160,1,B1,ICL_129B,absorbance,680_nm,0.0994,0.109013,-0.009613
578,2019-04-17,0,sc+c,160,1,C1,ICL_100,absorbance,680_nm,0.0949,0.109013,-0.014113
579,2019-04-17,0,sc+c,160,1,D1,ICL_101,absorbance,680_nm,0.0928,0.109013,-0.016213
580,2019-04-17,0,sc+c,160,1,E1,ICL_103,absorbance,680_nm,0.0933,0.109013,-0.015713
...,...,...,...,...,...,...,...,...,...,...,...,...
24859,2019-04-24,162,sc+c,160,1,D12,ICL_129A,fluorescence,680_nm,2.0000,3.424242,-1.424242
24860,2019-04-24,162,sc+c,160,1,E12,ICL_184BA,fluorescence,680_nm,726.0000,3.424242,722.575758
24861,2019-04-24,162,sc+c,160,1,F12,ICL_20BA,fluorescence,680_nm,942.0000,3.424242,938.575758
24862,2019-04-24,162,sc+c,160,1,G12,ICL_162,fluorescence,680_nm,719.0000,3.424242,715.575758
24863,2019-04-24,162,sc+c,160,1,H12,CHLAMY,fluorescence,680_nm,727.0000,3.424242,723.575758

# Segregate by Condition & Join Respective Wavelengths

    # recall that our models only require A680 and A750.
    # because of this we're going to ignore F680... there
    # are several reasons for ignoring this as well

# Condition B+C, B @ 680

In [11]:
A680 = dfscr[(dfscr['measurement_type']=='absorbance')&
             (dfscr['wavelength']=='680_nm')]
A680.shape

A680['samp_day'].unique() # note that its collected for only six days

# media-partioned A680 data: condition = 'bc'
df_cb160 = A680[(A680['c_b_ratio']=='160')&(A680['condition'] == 'b+c')]
df_cb16 = A680[(A680['c_b_ratio']=='16')&(A680['condition'] == 'b+c')]
df_cb_1p6 = A680[(A680['c_b_ratio']=='1.6')&(A680['condition'] == 'b+c')]
df_cb_0 = A680[(A680['c_b_ratio']=='-')&(A680['condition'] == 'b')]


df_cb160.shape
df_cb16.shape
df_cb_1p6.shape
df_cb_0.shape

daily_cb160_reps_dfs_680 = []
daily_cb16_reps_dfs_680 = []
daily_cb_1p6_reps_dfs_680 = []
daily_cb_0_reps_dfs_680 = []
for day in A680['samp_day'].unique():
    #day
    keep_cols = ['t(h)', 'well', 'replicate', 'content', 'measure', 'corr_measure']
    cb160 = df_cb160[(df_cb160['samp_day']==day)][keep_cols].reset_index(drop=True)
    cb16 = df_cb16[(df_cb16['samp_day']==day)][keep_cols].reset_index(drop=True)
    cb_1p6 = df_cb_1p6[(df_cb_1p6['samp_day']==day)][keep_cols].reset_index(drop=True)
    cb_0 = df_cb_0[(df_cb_0['samp_day']==day)][keep_cols].reset_index(drop=True)
    
    
    # ensure that the daily replicates have a mean 't(h)' column this helps
    # plot the information on a timewise manner much simpler
    try:
        for df in  [cb160, cb16, cb_1p6, cb_0]:
            df['t(h)'] = int(df['t(h)'].mean())
    except:
        day
        #df
        continue
    
    cb160 = cb160.rename({'measure':'A680', 'corr_measure':'A680c'}, axis=1)
    cb16 = cb16.rename({'measure':'A680', 'corr_measure':'A680c'}, axis=1)
    cb_1p6 = cb_1p6.rename({'measure':'A680', 'corr_measure':'A680c'}, axis=1)
    cb_0 = cb_0.rename({'measure':'A680', 'corr_measure':'A680c'}, axis=1)

    daily_cb160_reps_dfs_680.append(cb160)
    daily_cb16_reps_dfs_680.append(cb16)
    daily_cb_1p6_reps_dfs_680.append(cb_1p6)
    daily_cb_0_reps_dfs_680.append(cb_0)

(9216, 12)

array(['2019-04-17T00:00:00.000000000', '2019-04-18T00:00:00.000000000',
       '2019-04-19T00:00:00.000000000', '2019-04-20T00:00:00.000000000',
       '2019-04-21T00:00:00.000000000', '2019-04-22T00:00:00.000000000',
       '2019-04-23T00:00:00.000000000', '2019-04-24T00:00:00.000000000'],
      dtype='datetime64[ns]')

(1536, 12)

(1536, 12)

(1536, 12)

(1536, 12)

# Condition B+C, B @ 750

In [12]:
A750 = dfscr[(dfscr['measurement_type']=='absorbance')&
             (dfscr['wavelength']=='750_nm')]
A750.shape

A750['samp_day'].unique() 


df_cb160 = A750[(A750['c_b_ratio']=='160')&(A750['condition'] == 'b+c')]
df_cb16 = A750[(A750['c_b_ratio']=='16')&(A750['condition'] == 'b+c')]
df_cb_1p6 = A750[(A750['c_b_ratio']=='1.6')&(A750['condition'] == 'b+c')]
df_cb_0 = A750[(A750['c_b_ratio']=='-')&(A750['condition'] == 'b')]


daily_cb160_reps_dfs_750 = []
daily_cb16_reps_dfs_750 = []
daily_cb_1p6_reps_dfs_750 = []
daily_cb_0_reps_dfs_750 = []
for day in A750['samp_day'].unique():
    
    keep_cols = ['t(h)', 'well', 'replicate', 'content', 'measure', 'corr_measure']
    cb160 = df_cb160[(df_cb160['samp_day']==day)][keep_cols].reset_index(drop=True)
    cb16 = df_cb16[(df_cb16['samp_day']==day)][keep_cols].reset_index(drop=True)
    cb_1p6 = df_cb_1p6[(df_cb_1p6['samp_day']==day)][keep_cols].reset_index(drop=True)
    cb_0 = df_cb_0[(df_cb_0['samp_day']==day)][keep_cols].reset_index(drop=True)
    
    
    # ensure that the daily replicates have a mean 't(h)' column
    try:

        for df in  [cb160, cb16, cb_1p6, cb_0]:
            df['t(h)'] = int(df['t(h)'].mean())
    except:
        day
        #df
        continue
    
    cb160 = cb160.rename({'measure':'A750', 'corr_measure':'A750c'}, axis=1)
    cb16 = cb16.rename({'measure':'A750', 'corr_measure':'A750c'}, axis=1)
    cb_1p6 = cb_1p6.rename({'measure':'A750', 'corr_measure':'A750c'}, axis=1)
    cb_0 = cb_0.rename({'measure':'A750', 'corr_measure':'A750c'}, axis=1)
    
    
    daily_cb160_reps_dfs_750.append(cb160)
    daily_cb16_reps_dfs_750.append(cb16)
    daily_cb_1p6_reps_dfs_750.append(cb_1p6)
    daily_cb_0_reps_dfs_750.append(cb_0)

(9216, 12)

array(['2019-04-17T00:00:00.000000000', '2019-04-18T00:00:00.000000000',
       '2019-04-19T00:00:00.000000000', '2019-04-20T00:00:00.000000000',
       '2019-04-21T00:00:00.000000000', '2019-04-22T00:00:00.000000000',
       '2019-04-23T00:00:00.000000000', '2019-04-24T00:00:00.000000000'],
      dtype='datetime64[ns]')

# Concatenate B+C, B

In [13]:
# zip ensure that only lists of mathching size get put together, thus even though A750 DFs
# have 10 days worth of data they are limited by the length of A680 data, this matters
# because it makes no sense to apply the models to non-existing A680 data


############
### cb160 ###
############
cb160_final_daily_BC = []
for a6,a7 in zip(daily_cb160_reps_dfs_680, daily_cb160_reps_dfs_750):

    a6 = a6.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    a7 = a7.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    
    df = pd.concat([a6, a7], join='outer', axis=1).reset_index()
    
    cb160_final_daily_BC.append(df)
    
cb160_bc_df = pd.concat(cb160_final_daily_BC)

############
### cb16 ###
############
cb16_final_daily_BC = []
for a6,a7 in zip(daily_cb16_reps_dfs_680, daily_cb16_reps_dfs_750):

    a6 = a6.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    a7 = a7.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    df = pd.concat([a6, a7], join='outer', axis=1).reset_index()
    
    cb16_final_daily_BC.append(df)

cb16_bc_df = pd.concat(cb16_final_daily_BC)


############
### cb_1p6 ###
############
cb_1p6_final_daily_BC = []
for a6,a7 in zip(daily_cb_1p6_reps_dfs_680, daily_cb_1p6_reps_dfs_750):

    a6 = a6.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    a7 = a7.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    
    df = pd.concat([a6, a7], join='outer', axis=1).reset_index()
    
    cb_1p6_final_daily_BC.append(df)

cb_1p6_bc_df = pd.concat(cb_1p6_final_daily_BC)


############
### cb_0 ###
############
cb_0_final_daily_BC = []
for a6,a7 in zip(daily_cb_0_reps_dfs_680, daily_cb_0_reps_dfs_750):

    a6 = a6.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    a7 = a7.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    
    df = pd.concat([a6, a7], join='outer', axis=1).reset_index()
    
    cb_0_final_daily_BC.append(df)

    
cb_0_bc_df = pd.concat(cb_0_final_daily_BC)

In [14]:
cb160_bc_df['b_c_ratio'] = '160'
cb16_bc_df['b_c_ratio'] = '16'
cb_1p6_bc_df['b_c_ratio'] = '1.6'
cb_0_bc_df['b_c_ratio'] = '-'

bc_dfs = [cb160_bc_df, cb16_bc_df, cb_1p6_bc_df, cb_0_bc_df]

bcdfs = pd.concat(bc_dfs).reset_index(drop=True)

bcdfs
path = '../data_o/screens/screens_preprocessed_data'
fname = 'sc4_non_supernatant_test_ratios_condition_b+c.csv'


#bcdfs.to_csv(pjoin(path, fname))
# save to disk

,t(h),well,replicate,content,A680,A680c,A750,A750c,b_c_ratio
0,0,A1,2,ICL_186B,0.1697,0.060687,0.1663,0.058233,160
1,0,B1,2,ICL_129B,0.1641,0.055087,0.1604,0.052333,160
2,0,C1,2,ICL_100,0.1565,0.047487,0.1517,0.043633,160
3,0,D1,2,ICL_101,0.1552,0.046187,0.1490,0.040933,160
4,0,E1,2,ICL_103,0.1558,0.046787,0.1493,0.041233,160
...,...,...,...,...,...,...,...,...,...
6139,162,D12,1,ICL_129A,0.1137,0.004687,0.1155,0.007433,-
6140,162,E12,1,ICL_184BA,0.1078,-0.001213,0.1082,0.000133,-
6141,162,F12,1,ICL_20BA,0.1163,0.007287,0.1160,0.007933,-
6142,162,G12,1,ICL_162,0.1131,0.004087,0.1131,0.005033,-
6143,162,H12,1,BLANK,0.1030,-0.006013,0.1034,-0.004667,-

# Condition SC+C, B @ 680

In [15]:
A680 = dfscr[(dfscr['measurement_type']=='absorbance')&
             (dfscr['wavelength']=='680_nm')]
A680.shape

A680['samp_day'].unique() # note that its collected for only six days

# media-partioned A680 data: condition = 'bc'
df_cb160 = A680[(A680['c_b_ratio']=='160')&(A680['condition'] == 'sc+c')]
df_cb16 = A680[(A680['c_b_ratio']=='16')&(A680['condition'] == 'sc+c')]
df_cb_1p6 = A680[(A680['c_b_ratio']=='1.6')&(A680['condition'] == 'sc+c')]
df_cb_0 = A680[(A680['c_b_ratio']=='-')&(A680['condition'] == 'sc')]


df_cb160.shape
df_cb16.shape
df_cb_1p6.shape
df_cb_0.shape

daily_cb160_reps_dfs_680 = []
daily_cb16_reps_dfs_680 = []
daily_cb_1p6_reps_dfs_680 = []
daily_cb_0_reps_dfs_680 = []
for day in A680['samp_day'].unique():
    #day
    keep_cols = ['t(h)', 'well', 'replicate', 'content', 'measure', 'corr_measure']
    cb160 = df_cb160[(df_cb160['samp_day']==day)][keep_cols].reset_index(drop=True)
    cb16 = df_cb16[(df_cb16['samp_day']==day)][keep_cols].reset_index(drop=True)
    cb_1p6 = df_cb_1p6[(df_cb_1p6['samp_day']==day)][keep_cols].reset_index(drop=True)
    cb_0 = df_cb_0[(df_cb_0['samp_day']==day)][keep_cols].reset_index(drop=True)
    
    
    # ensure that the daily replicates have a mean 't(h)' column this helps
    # plot the information on a timewise manner much simpler
    try:
        for df in  [cb160, cb16, cb_1p6, cb_0]:
            df['t(h)'] = int(df['t(h)'].mean())
    except:
        day
        #df
        continue
    
    cb160 = cb160.rename({'measure':'A680', 'corr_measure':'A680c'}, axis=1)
    cb16 = cb16.rename({'measure':'A680', 'corr_measure':'A680c'}, axis=1)
    cb_1p6 = cb_1p6.rename({'measure':'A680', 'corr_measure':'A680c'}, axis=1)
    cb_0 = cb_0.rename({'measure':'A680', 'corr_measure':'A680c'}, axis=1)

    daily_cb160_reps_dfs_680.append(cb160)
    daily_cb16_reps_dfs_680.append(cb16)
    daily_cb_1p6_reps_dfs_680.append(cb_1p6)
    daily_cb_0_reps_dfs_680.append(cb_0)

(9216, 12)

array(['2019-04-17T00:00:00.000000000', '2019-04-18T00:00:00.000000000',
       '2019-04-19T00:00:00.000000000', '2019-04-20T00:00:00.000000000',
       '2019-04-21T00:00:00.000000000', '2019-04-22T00:00:00.000000000',
       '2019-04-23T00:00:00.000000000', '2019-04-24T00:00:00.000000000'],
      dtype='datetime64[ns]')

(768, 12)

(768, 12)

(768, 12)

(768, 12)

# Condition SC+C, B @ 750

In [16]:
A750 = dfscr[(dfscr['measurement_type']=='absorbance')&
             (dfscr['wavelength']=='750_nm')]
A750.shape

A750['samp_day'].unique() # note that its collected for only six days


# media-partioned A680 data: condition = 'bc'
df_cb160 = A750[(A750['c_b_ratio']=='160')&(A750['condition'] == 'sc+c')]
df_cb16 = A750[(A750['c_b_ratio']=='16')&(A750['condition'] == 'sc+c')]
df_cb_1p6 = A750[(A750['c_b_ratio']=='1.6')&(A750['condition'] == 'sc+c')]
df_cb_0 = A750[(A750['c_b_ratio']=='-')&(A750['condition'] == 'sc')]

df_cb160.shape
df_cb16.shape
df_cb_1p6.shape
df_cb_0.shape

# there are 6 DFs in the lists below, each houses 3 different sets of strains ('replicates')
daily_cb160_reps_dfs_750 = []
daily_cb16_reps_dfs_750 = []
daily_cb_1p6_reps_dfs_750 = []
daily_cb_0_reps_dfs_750 = []
for day in A750['samp_day'].unique():
    keep_cols = ['t(h)', 'well', 'replicate', 'content', 'measure', 'corr_measure']
    cb160 = df_cb160[(df_cb160['samp_day']==day)][keep_cols].reset_index(drop=True)
    cb16 = df_cb16[(df_cb16['samp_day']==day)][keep_cols].reset_index(drop=True)
    cb_1p6 = df_cb_1p6[(df_cb_1p6['samp_day']==day)][keep_cols].reset_index(drop=True)
    cb_0 = df_cb_0[(df_cb_0['samp_day']==day)][keep_cols].reset_index(drop=True)
    
    
    # ensure that the daily replicates have a mean 't(h)' column
    try:

        for df in  [cb160, cb16, cb_1p6, cb_0]:
            df['t(h)'] = int(df['t(h)'].mean())
    except:
        day
        #df
        continue
    
    cb160 = cb160.rename({'measure':'A750', 'corr_measure':'A750c'}, axis=1)
    cb16 = cb16.rename({'measure':'A750', 'corr_measure':'A750c'}, axis=1)
    cb_1p6 = cb_1p6.rename({'measure':'A750', 'corr_measure':'A750c'}, axis=1)
    cb_0 = cb_0.rename({'measure':'A750', 'corr_measure':'A750c'}, axis=1)
    
    
    daily_cb160_reps_dfs_750.append(cb160)
    daily_cb16_reps_dfs_750.append(cb16)
    daily_cb_1p6_reps_dfs_750.append(cb_1p6)
    daily_cb_0_reps_dfs_750.append(cb_0)

(9216, 12)

array(['2019-04-17T00:00:00.000000000', '2019-04-18T00:00:00.000000000',
       '2019-04-19T00:00:00.000000000', '2019-04-20T00:00:00.000000000',
       '2019-04-21T00:00:00.000000000', '2019-04-22T00:00:00.000000000',
       '2019-04-23T00:00:00.000000000', '2019-04-24T00:00:00.000000000'],
      dtype='datetime64[ns]')

(768, 12)

(768, 12)

(768, 12)

(768, 12)

# Concatenate SC+C, SC

In [17]:
# zip ensure that only lists of mathching size get put together, thus even though A750 DFs
# have 10 days worth of data they are limited by the length of A680 data, this matters
# because it makes no sense to apply the models to non-existing A680 data


############
### cb160 ###
############
cb160_final_daily_SC = []
for a6,a7 in zip(daily_cb160_reps_dfs_680, daily_cb160_reps_dfs_750):

    a6 = a6.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    a7 = a7.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    
    df = pd.concat([a6, a7], join='outer', axis=1).reset_index()
    
    cb160_final_daily_SC.append(df)
    
cb160_sc_df = pd.concat(cb160_final_daily_SC)

############
### cb16 ###
############
cb16_final_daily_SC = []
for a6,a7 in zip(daily_cb16_reps_dfs_680, daily_cb16_reps_dfs_750):

    a6 = a6.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    a7 = a7.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    df = pd.concat([a6, a7], join='outer', axis=1).reset_index()
    
    cb16_final_daily_SC.append(df)

cb16_sc_df = pd.concat(cb16_final_daily_SC)


############
### cb_1p6 ###
############
cb_1p6_final_daily_SC = []
for a6,a7 in zip(daily_cb_1p6_reps_dfs_680, daily_cb_1p6_reps_dfs_750):

    a6 = a6.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    a7 = a7.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    
    df = pd.concat([a6, a7], join='outer', axis=1).reset_index()
    
    cb_1p6_final_daily_SC.append(df)

cb_1p6_sc_df = pd.concat(cb_1p6_final_daily_SC)


############
### cb_0 ###
############
cb_0_final_daily_SC = []
for a6,a7 in zip(daily_cb_0_reps_dfs_680, daily_cb_0_reps_dfs_750):

    a6 = a6.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    a7 = a7.set_index(keys=['t(h)', 'well','replicate', 'content'])#, drop=True)
    
    df = pd.concat([a6, a7], join='outer', axis=1).reset_index()
    
    cb_0_final_daily_SC.append(df)

    
cb_0_sc_df = pd.concat(cb_0_final_daily_SC)

In [18]:
cb160_sc_df['b_c_ratio'] = '160'
cb16_sc_df['b_c_ratio'] = '16'
cb_1p6_sc_df['b_c_ratio'] = '1.6'
cb_0_sc_df['b_c_ratio'] = '-'

sc_dfs = [cb160_sc_df, cb16_sc_df, cb_1p6_sc_df, cb_0_sc_df]

scdfs = pd.concat(sc_dfs).reset_index(drop=True)
scdfs

path = '../data_o/screens/screens_preprocessed_data'
fname = 'sc4_non_supernatant_test_ratios_condition_sc+c.csv'


#scdfs.to_csv(pjoin(path, fname))
# save to disk

,t(h),well,replicate,content,A680,A680c,A750,A750c,b_c_ratio
0,0,A1,1,ICL_186B,0.0898,-0.019213,0.0944,-0.013667,160
1,0,B1,1,ICL_129B,0.0994,-0.009613,0.1007,-0.007367,160
2,0,C1,1,ICL_100,0.0949,-0.014113,0.0981,-0.009967,160
3,0,D1,1,ICL_101,0.0928,-0.016213,0.0966,-0.011467,160
4,0,E1,1,ICL_103,0.0933,-0.015713,0.0984,-0.009667,160
...,...,...,...,...,...,...,...,...,...
3067,162,D12,1,ICL_129A,0.1133,0.004287,0.1138,0.005733,-
3068,162,E12,1,ICL_184BA,0.1168,0.007787,0.1145,0.006433,-
3069,162,F12,1,ICL_20BA,0.1067,-0.002313,0.1048,-0.003267,-
3070,162,G12,1,ICL_162,0.1196,0.010587,0.1174,0.009333,-
3071,162,H12,1,BLANK,0.1101,0.001087,0.1092,0.001133,-